name: Bug Report
description: Report a bug to help us improve VibeFlow
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
      placeholder: Describe the bug...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: VibeFlow Version
      description: What version of VibeFlow are you using? (e.g., v0.3.3)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 10
        - Windows 11
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant logs here.
      render: shell
