name: Feature Request
description: Suggest an idea for VibeFlow
labels: [enhancement]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: why-needed
    attributes:
      label: Why is this feature needed?
      description: Tell us why this feature would be useful.
    validations:
      required: true
